import type { Product } from './slices/productsSlice'

export const mockProducts: Product[] = [
	{
		id: '1',
		title: 'Ezine Koyun Peyniri 600g',
		slug: 'ezine-koyun-peyniri-600g',
		price: 349.9,
		image: '/images/peynir-ezine.jpg',
		category: 'peynir',
		description: 'Marmara bölgesinden, tam yağlı koyun sütünden üretilmiş Ezine peyniri.',
		badges: ['Popüler']
	},
	{
		id: '2',
		title: 'Trakya Eski Kaşar 500g',
		slug: 'trakya-eski-kasar-500g',
		price: 289.5,
		image: '/images/kasar-trakya.jpg',
		category: 'peynir',
		description: 'Uzun süre dinlendirilmiş tam kıvamında eski kaşar.',
	},
	{
		id: '3',
		title: 'Gemlik Siyah Zeytin 1kg',
		slug: 'gemlik-siyah-zeytin-1kg',
		price: 229.0,
		image: '/images/zeytin-gemlik.jpg',
		category: 'zeytin',
		description: 'Kahvaltıların vazgeçilmezi, etli ve az tuzlu Gemlik zeytini.',
	},
	{
		id: '4',
		title: 'Süzme Çiçek Balı 850g',
		slug: 'suzme-cicek-bali-850g',
		price: 199.9,
		image: '/images/bal-cicek.jpg',
		category: 'bal',
		description: 'Yüksek rakım yaylalarından doğal süzme bal.',
	},
	{
		id: '5',
		title: 'Kars Gravyeri 400g',
		slug: 'kars-gravyeri-400g',
		price: 379.0,
		image: '/images/gravyer-kars.jpg',
		category: 'peynir',
		description: 'Kars yöresine özgü, zengin aromalı gravyer peyniri.',
	},
	{
		id: '6',
		title: 'Yeşil Kırma Zeytin 1kg',
		slug: 'yesil-kirma-zeytin-1kg',
		price: 189.9,
		image: '/images/zeytin-yesil.jpg',
		category: 'zeytin',
		description: 'Ege’den hafif tuzlu, limonlu salamurada kırma zeytin.',
	},
	{
		id: '7',
		title: 'Çam Balı 850g',
		slug: 'cam-bali-850g',
		price: 209.9,
		image: '/images/bal-cam.jpg',
		category: 'bal',
		description: 'Doğal çam balı, koyu renk ve yoğun lezzet.',
	},
	{
		id: '8',
		title: 'Lor Peyniri 500g',
		slug: 'lor-peyniri-500g',
		price: 79.9,
		image: '/images/lor.jpg',
		category: 'peynir',
		description: 'Kahvaltılık ve börekler için hafif lor peyniri.',
	},
]
